In [27]:
A=np.matrix('3 -5 3;1,2,1;2,7,-1')
B=np.matrix('1;4;8')
print('A=',A)
print('B=',B)
A_inv=np.linalg.inv(A)
print(A_inv)
X=A_inv.dot(B)
print('X=',X)

A= [[ 3 -5  3]
 [ 1  2  1]
 [ 2  7 -1]]
B= [[1]
 [4]
 [8]]
[[ 0.27272727 -0.48484848  0.33333333]
 [-0.09090909  0.27272727  0.        ]
 [-0.09090909  0.93939394 -0.33333333]]
X= [[1.]
 [1.]
 [1.]]
